entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: oseiasal@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
