global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'n8n'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['10.0.1.169:9100']