- name: Criar volume para n8n
  community.docker.docker_volume:
    name: n8n_data
    state: present

- name: Executar n8n no Docker
  community.docker.docker_container:
    name: n8n
    image: docker.n8n.io/n8nio/n8n
    state: started
    restart_policy: unless-stopped
    ports:
      - "5678:5678"
    env:
      GENERIC_TIMEZONE: "Europe/Berlin"
      TZ: "Europe/Berlin"
    volumes:
      - n8n_data:/home/node/.n8n
  ignore_errors: yes